# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lookup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clookup.proto\x12\ndnsResolve\"r\n\x0b\x44nsQuestion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x36\n\nrrdatatype\x18\x02 \x01(\x0e\x32\".dnsResolve.DnsQuestion.RRDataType\"\x1d\n\nRRDataType\x12\x05\n\x01\x41\x10\x00\x12\x08\n\x04\x41\x41\x41\x41\x10\x01\"\x16\n\x06\x41nswer\x12\x0c\n\x04json\x18\x01 \x01(\t2D\n\x08Resolver\x12\x38\n\x07Resolve\x12\x17.dnsResolve.DnsQuestion\x1a\x12.dnsResolve.Answer\"\x00\x62\x06proto3')



_DNSQUESTION = DESCRIPTOR.message_types_by_name['DnsQuestion']
_ANSWER = DESCRIPTOR.message_types_by_name['Answer']
_DNSQUESTION_RRDATATYPE = _DNSQUESTION.enum_types_by_name['RRDataType']
DnsQuestion = _reflection.GeneratedProtocolMessageType('DnsQuestion', (_message.Message,), {
  'DESCRIPTOR' : _DNSQUESTION,
  '__module__' : 'lookup_pb2'
  # @@protoc_insertion_point(class_scope:dnsResolve.DnsQuestion)
  })
_sym_db.RegisterMessage(DnsQuestion)

Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), {
  'DESCRIPTOR' : _ANSWER,
  '__module__' : 'lookup_pb2'
  # @@protoc_insertion_point(class_scope:dnsResolve.Answer)
  })
_sym_db.RegisterMessage(Answer)

_RESOLVER = DESCRIPTOR.services_by_name['Resolver']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DNSQUESTION._serialized_start=28
  _DNSQUESTION._serialized_end=142
  _DNSQUESTION_RRDATATYPE._serialized_start=113
  _DNSQUESTION_RRDATATYPE._serialized_end=142
  _ANSWER._serialized_start=144
  _ANSWER._serialized_end=166
  _RESOLVER._serialized_start=168
  _RESOLVER._serialized_end=236
# @@protoc_insertion_point(module_scope)
